### ISSUE TITLE
please build it from sources

### ISSUE THREAD

**Issue by abucodonosor** [KaOS-Community-Packages/vscode#2]
Also since the source code exists why don't you 'build' this one from sources ?

https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

thx

**Comment by padhia** [comment]
What additional features will be available by building from source that are currently missing from packaging binary image?

**Comment by demmm** [comment]
Looks at this stage this issue should be closed, the upstream shipped binary used here has significantly more features due to the fact that a from source build does not support the extension gallery.
https://code.visualstudio.com/docs/editor/extension-gallery

**Comment by padhia** [comment]
Closing due to no response from the OP.
