### ISSUE TITLE
vscode vs code symlink

### ISSUE THREAD

**Issue by karlprieb** [KaOS-Community-Packages/vscode#3]
Can we add `ln -s /opt/vscode/bin/code ${pkgdir}/usr/bin/code` too?
So we can call the app using `vscode` and `code` like all other distros?

**Comment by ShalokShalom** [comment]
I guess thats what people expect, when they come from other distros. Its also what I used in private builds. It's already hard enough to find, since only in KCP (yet). I vote for it :+1: 

Thanks a lot for caring about this, recent builds failed to build for me, great work :D

**Comment by karlprieb** [comment]
@ShalokShalom thank you for answer :) I'll update this package.

Which problems do you have when building this package? Can you open an issue for that?

**Comment by karlprieb** [comment]
Added the `code` symlink 377260acedaf6415ca809e98ba3c0d967dfa365e
